### ISSUE TITLE
Find a way to allow for "watch -d qtop" visualization WITH color

### ISSUE THREAD

**Issue by sfranky** [sfranky/qtop#13]

**Comment by fgeorgatos** [comment]
as discussed, watch -d -c exists only on _some_ systems (certainly not rhel6*), so this is still valid

**Comment by sfranky** [comment]
-c AUTO should autodetect controlling terminal. Otherwise, -c ON and -c OFF as options

**Comment by fgeorgatos** [comment]
this is implemented via #85
