### ISSUE TITLE
[VIS] Remapping file

### ISSUE THREAD

**Issue by sfranky** [sfranky/qtop#19]
User should be able to decide on node naming, by providing a remap mapping file, such as:
torvalds --> tor
stroustrup --> strou
chomsky --> chm
workernode250.blahblah-workernode450.blahblah --> wn001-wn250

**Comment by fgeorgatos** [comment]
Nai, ayto to issue einai sxetika eykolo kai poly generic, opote aksizei thn prosoxi mas se ayto to stadio!

**Comment by sfranky** [comment]
to teleutaio:
workernode250.blahblah-workernode450.blahblah --> wn001-wn250
praktika, 
workernode250-workernode450 --> wn001-wn250 
einai trickier.
na to afisw gia twra??
