### ISSUE TITLE
Sorting discrepancy

### ISSUE THREAD

**Issue by sfranky** [sfranky/qtop#22]
**file**: gef_8e3OrbuWti6wAR59UMqR7Q/QTOP.OUT

check unix account **llr199**
**fotis**: id: B, 0+2/2
**me**: id: E, 0+2/2, but much lower in the ranking.
fotis also has other 0+2/2 ids much later
![ranking_discrepancy](https://cloud.githubusercontent.com/assets/1530259/9533035/023c96c0-4d18-11e5-9606-09fc523f2180.png)

**Comment by fgeorgatos** [comment]
yeap; you have a point.
what is the output of command `grep llr199 qstat.out` ? the answer will be hidden there!

**Comment by fgeorgatos** [comment]
and also, why cmspliot002 is in different plce in the right output? that's a bit weird;
I suspect that the sorting tuple is with the columns (all, unix account), that's what it seems like and it makes sense for improved stability in the output

**Comment by fgeorgatos** [comment]
yes, the more I think about it, the more descending (all, unix account) makes sense for both of the above

**Comment by sfranky** [comment]
yeap, you were right. Fixed! still need to fix unsorted ids mess though! (broken)
