### ISSUE TITLE
where to place configuration file

### ISSUE THREAD

**Issue by sfranky** [sfranky/qtop#32]
Do we supply a full example qtopconf.yaml in the current dir (how would it be placed elsewhere?)
and at the some time check for a user-placed conf file in $HOME/.local/qtop which should override the default one?

**Comment by fgeorgatos** [comment]
```
/etc/qtopconf.yaml
./qtopconf.yaml
$HOME/.local/qtop/qtopconf.yaml
```
similarly, for all other configs (colormaps etc)

I'd assume dirs in that order of priority..

**Comment by sfranky** [comment]
Done for this conf file. colormap is a module for now.
