### ISSUE TITLE
check all following commands for extra utility and write appropriate parsers for it

### ISSUE THREAD

**Issue by sfranky** [sfranky/qtop#33]
qstat_-g_c
qstat_-g_t
qstat_-g_t_-u_*
qstat
qstat_-f
qstat_-F
qstat_-F_-r
qstat_-r
qhost
qhost_-j
qhost_-q

**Comment by fgeorgatos** [comment]
SGE can deliver now all information via `qstat -F -xml -u '*'`, which is great for atomicity of info sources; 
so the above is deprecated by now
