### ISSUE TITLE
Allow multiple concurrent runs

### ISSUE THREAD

**Issue by sfranky** [sfranky/qtop#9]
Reentrant code - how to ensure that multiple users can run the code concurrently (even if from the same unix account)
Improve code quality.

**Comment by sfranky** [comment]
check mktemp solution. for now appending the pid seems to do the job

**Comment by fgeorgatos** [comment]
see #44:
avoid creation of and reliance on files such as `qstat_txtyaml.yaml`, which would SPOF if run multiple times in the same dir (fi. /tmp). Use instead `mktemp` if intermediate files are absolutely necessary.

**Comment by sfranky** [comment]
should be fixed.
